<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RecipeRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{

    public function findRecipesWithoutOrder() {

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult("AppBundle:Recipe", "r")
            ->addFieldResult("r", "id", "id")
            ->addFieldResult("r", "title", "title")
            ->addFieldResult("r", "photo", "photo")
            ->addFieldResult("r", "nb_likes", "nbLikes")
            ->addFieldResult("r", "created_at", "createdAt");

        $query = <<<SQL
            SELECT r.id, r.title, r.photo, r.nb_likes, r.created_at
            FROM recipe r
            ORDER BY RAND()
SQL;

        $result = $this->getEntityManager()->createNativeQuery($query, $rsm)->getResult();
        return $result;

    }


    public function findRecipesByName($name) {

        $rsm = new ResultSetMapping();
        $rsm->addEntityResult("AppBundle:Recipe", "r")
            ->addFieldResult("r", "id", "id")
            ->addFieldResult("r", "title", "title")
            ->addFieldResult("r", "photo", "photo")
            ->addFieldResult("r", "nb_likes", "nbLikes")
            ->addFieldResult("r", "created_at", "createdAt");

        $query = <<<SQL
            SELECT r.id, r.title, r.photo, r.nb_likes, r.created_at
            FROM recipe r
            WHERE title LIKE ?
SQL;

        $result = $this->getEntityManager()->createNativeQuery($query, $rsm)->setParameters(array("%".$name."%"))->getResult();
        return $result;

    }

}
